### ISSUE TITLE
backup/restore operators?

### ISSUE THREAD

**Issue by davidsiefert** [spotahome/redis-operator#105]
### Expected behaviour

Would like to have redis backed up on a schedule (say every 30m) and have the backup file (optionally) encrypted, compressed, and uploaded to a storage bucket (s3 or gcp cloud storage) keeping last _n_ backups. Likewise, would need a restore operator to download a backup, decompress, (optionally) decrypt and load into redis.

Would this be out of scope for this operator? Although there are follower replicas to be promoted, it might be useful to have a backup/restore operator for catastrophic failures. Before continuing discussion of implementation approaches in the PR, I would like to get a consensus on the value of having this. :+1:?

**Comment by jchanam** [comment]
Hi @davidsiefert,

I understand this has a good value, but I'm not sure if this is the scope of the operator.

Currently, there are the possibility of having persistence into `persistent volumes`, making redis to write into a file it's whole database. Once activated, that file could be copied from the folder and saved somewhere else.

**Comment by Hades32** [comment]
So, I'm currently working around this missing feature with this manual CronJob, which works nicely:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: redis-backup
  namespace: suntracker
spec:
  schedule: '52 19 * * *'
  jobTemplate:
    metadata:
      name: redis-backup
      namespace: suntracker
    spec:
      template:
        metadata:
          name: redis-backup
          namespace: suntracker
        spec:
          restartPolicy: Never
          containers:
            - image: d3fk/s3cmd
              command:
                - sh
                - -c
                - |
                  tar czf /tmp/redis-bak-$(date -u -Iseconds).tar.gz /data/*.*
                  s3cmd --region=nl-ams --host=https://s3.nl-ams.scw.cloud --host-bucket=https://s3.nl-ams.scw.cloud \
                    --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY \
                    put /tmp/redis-bak-* s3://$S3_BUCKET/suntracker/
              name: redis-backup
              envFrom:
                - secretRef:
                    name: s3-secret
              volumeMounts:
                - mountPath: /data
                  name: redis-data
          volumes:
            - name: redis-data
              persistentVolumeClaim:
                claimName: suntracker-redis-data-rfr-suntracker-redis-0
```

BUT the big issue as you can see, is that I need to have a secret containing all important info about the S3 Bucket. Is is of course a problem, especially if the user creating the Redis instance is not the user creating the infrastructure.

Maybe some light-weight option would be possible...
