### ISSUE TITLE
How to set client-output-buffer-limit?

### ISSUE THREAD

**Issue by rhefner1** [spotahome/redis-operator#118]
Hi @jchanam, thanks again for the great project. We've been running in production for a few months now and things seem to be pretty good.

However, we recently had some trouble with our redis cluster due to the slaves exceeding their output buffer limits, so I need to set this in the operator config. Here is the relevant part of my config file:

```
    redis:
      replicas: 3
      image: "redis"
      version: "3.2-alpine"
  
      customConfig:
        - "tcp-keepalive 60"
        - client-output-buffer-limit \"normal 0 0 0 slave 1000000000 1000000000 0 pubsub 33554432 8388608 60\"
```

Note that I've tried a number of combinations (without `\"`, with it, etc.) and each time I get the error message below in the operator logs:

```
time="2019-02-21T16:41:25Z" level=error msg="Error processing staging/staging-sandbox-redis-ha: ERR Wrong number of arguments for CONFIG set" controller=redisfailover operator=redisfailover src="generic.go:223"
```

Running `config set client-output-buffer-limit "normal 0 0 0 slave 1000000000 1000000000 0 pubsub 33554432 8388608 60"` directly in redis-cli works just fine. How can I express this in the operator?

**Comment by jchanam** [comment]
Hi @rhefner1,

I'll try to reproduce and update you if I find a fix. Have you tried with the following?

```
    redis:
      replicas: 3
      image: "redis"
      version: "3.2-alpine"
  
      customConfig:
        - "tcp-keepalive 60"
        - "client-output-buffer-limit 'normal 0 0 0 slave 1000000000 1000000000 0 pubsub 33554432 8388608 60'"
```
