### ISSUE TITLE
There is a way to set diff image from 3.2-alpine to 5.0.3-alpine ? 

### ISSUE THREAD

**Issue by RotemEmergi** [spotahome/redis-operator#134]
Hi ,

I use the basic way to deploy the cluster , I want to knew if there is a way to change the image tag ?

Best Regards

**Comment by RotemEmergi** [comment]
I also see that it's can change in  the default.go in the api part , there is a way to change it ? (or explain how to build it ) 

Thanks !

**Comment by jchanam** [comment]
Hi,

The image you're mentioning is the one used by default, but you can use the one you want in every `redisfailover` you create.

You can find an example (I've just added it) in [redis-operator/example/redisfailover/custom-image.yaml](https://github.com/spotahome/redis-operator/blob/5c0df52c3b8c096d05444cf575934724a119bfb5/example/redisfailover/custom-image.yaml#L1-L11)

**Comment by RotemEmergi** [comment]
Hi ! 

But i see that that in the api the default is 3.2 .
`defaultRedisImageVersion    = "3.2-alpine"` .

How I need to deploy :  
1. kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
2. Deploy this basic yaml 
```yaml
apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    image: redis
    version: 5.0.4-alpine
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    image: redis
    version: 5.0.4-alpine
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
```

**Comment by jchanam** [comment]
Yes, that's the default version if no version is specified in the `redisfailover` to be created.

To deploy, you're saying it right. First you deploy the operator. After that, you can create instances of `redisfailover`, that the operator will take care of and will create all the resources needed.

In your yaml, the image and version on sentinel is not used, as they are shared (and it's readed from redis definition).

```
apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    image: redis
    version: 5.0.4-alpine
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
```
