### ISSUE TITLE
Shutdown script permission denied

### ISSUE THREAD

**Issue by ShakataGaNai** [spotahome/redis-operator#162]
### Expected behaviour

Shutdown script on redis pod executing properly

### Actual behaviour

`Exec lifecycle hook ([/bin/sh -c /redis-shutdown/shutdown.sh]) for Container "redis" in Pod "rfr-testcluster-redis-1_default(012fff57-7e64-11e9-9544-0cc47aace4ea)" failed - error: command '/bin/sh -c /redis-shutdown/shutdown.sh' exited with 126: /bin/sh: /redis-shutdown/shutdown.sh: Permission denied , message: "/bin/sh: /redis-shutdown/shutdown.sh: Permission denied\n"`

### Steps to reproduce the behaviour

* kubectl create -f https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
* kubectl apply the following
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: testcluster-redis
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 1000m
        memory: 1G
      limits:
        cpu: 2000m
        memory: 4G
```
* Wait till up and running. Then delete one (rfr-testcluster-redis-*) at random. I picked the master. This was done through the dashboard, but it could be CLI. During proper shutdown procedures, the above error surfaced.

### Environment

How are the pieces configured?
* Redis Operator version -- Created this today (2019-05-24) so master version. Unable to find any version logging.
* Kubernetes version -- 1.13.5.
* Kubernetes configuration used (eg: Is RBAC active?) -- Yes RBAC, per 1.13 defaults. Cluster created a few days ago using rancher/rke v0.2.2

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
