### ISSUE TITLE
Custom Annotations for Services and Pods

### ISSUE THREAD

**Issue by alecjacobs5401** [spotahome/redis-operator#166]
### Expected behaviour

Custom annotations for the Redis StatefulSet and Sentinel Pods should be applied to the respective pods based on the `RedisFailover` yml configuration.

### Actual behaviour

Annotations cannot be applied from the `RedisFailover` yml configuration

### Steps to reproduce the behaviour

1. Define `RedisFailover` yml configuration as follows
```yml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    podAnnotations:
      some:
        annotations: here
  redis:
    replicas: 3
    podAnnotations:
      some:
        annotations: here
```
2. Apply configuration
3. `kubectl describe pod <redis-pod,sentinel-pod>
4. See Annotations.
### Environment
**N/A - Feature Request**

### Logs
**N/A - Feature Request**

I'd be happy to give this a shot at implementation if this is a feature deemed usable. The alternative is to just manually apply any annotations after launching the `redisfailover` CRD, but thats just another manual step that could live source controlled with the actual `RedisFailover` configuration.
