### ISSUE TITLE
For an offline K8s configuration, the Docker image being pulled every time although the Docker image is present on local machine

### ISSUE THREAD

**Issue by bendemistim** [spotahome/redis-operator#174]
### Expected behaviour

For an offline K8s configuration, when applying basic.yaml, when necessary Docker images are present locally, it should not try to go online to pull the images at all.

### Actual behaviour

For an offline K8s cluster, we saved and loaded all necessary docker images with correct tags, etc. 

Despite this, each time a pod is being initialized, it immediately switches to Image Pull Back error state.

When we look at the logs using describe command, we can clearly see that it finds the necessary image locally but tries to pull the image from online Docker hub.

Note: When applying all-redis-operator-resources.yaml, we do not face this issue. (Docker image used for all-redis-operator-resources.yaml file is redis-operator:latest and for basic.yaml, it is redis:latest or redis:5-0-alpine)

### Environment

How are the pieces configured?
* Redis Operator version: v1
* Kubernetes version: v1.14

**Comment by marcemq** [comment]
Hi there 😊 

To which images are referring to?  I got a bit confused.

If you're referring to operator images and ff you're installing the operator trough:
- `helm`, then you need to specify/change the `pullPolicy: IfNotPresent` at [values.yaml ](https://github.com/spotahome/redis-operator/blob/master/charts/redisoperator/values.yaml)
- `all-redis-operator-resources.yaml` the pull policy is already set to `IfNotPresent` and that's why you're not having issues with it.

I hope this explanation helps.

**Comment by bendemistim** [comment]
Hello @marcemq 

I was referring to Docker images.

I am not using Helm. I'm using the two yaml files directly with kubectl:

For operator:

https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml

For failovers:

https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover/basic.yaml

The Docker image being used in the first yaml is fine with offline K8s deployment but the latter one makes use of a redis Docker image and although it is present in my local Docker registry, K8s pod initialization tries to pull the image over the Internet although it can successfully detect the necessary Docker image locally.

**Comment by marcemq** [comment]
Hello and thanks for the clarification @bendemistim! 😊 

You can try to deploy a `basic.yaml` adding the usage of `image`, `version` and `pullPolicy` same as [example/redisfailover/pmem.yaml](https://github.com/spotahome/redis-operator/blob/master/example/redisfailover/pmem.yaml#L20-L21) and [example/redisfailover/custom-image.yaml](https://github.com/spotahome/redis-operator/blob/master/example/redisfailover/custom-image.yaml)

**Comment by bendemistim** [comment]
Hello,

We're still getting image pull back error when we try in offline mode. We tried all flavors for `pullPolicy `to no avail.

Here are the logs of the related pod:

```
-Successfully assigned default/rfs-redisfailover-57c798d94c-p4hfb to app-2
-Container image "redis:5.0-alpine" already present on machine
-Created container sentinel-config-copy
-Started container sentinel-config-copy
-Failed to pull image "redis:5.0-alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on [::1]:53: read udp [::1]:55839->[::1]:53: read: connection refused
```

However, we already have the docker image on the machine (even the second line above confirms it), please see attachment, docker ls output:

[https://cdn1.imggmi.com/uploads/2019/8/26/0e0071708f585886a598b8e07297c977-full.png](url)

I am attaching our yaml files for your reference. We're using these two for the Redis configuration.

**basic.yaml**

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    image: redis:5.0-alpine
    imagePullPolicy: Never
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    affinity:
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - sentinel
            topologyKey: "kubernetes.io/hostname"
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/app
                operator: In
                values:
                - ""
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - "app"
  redis:
    replicas: 3
    image: redis:5.0-alpine
    imagePullPolicy: Never
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    affinity:
      podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - redis
            topologyKey: "kubernetes.io/hostname"
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/app
                operator: In
                values:
                - ""
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - "app"
```

**redis.yaml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisoperator
  name: redisoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisoperator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redisoperator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - app        
      serviceAccountName: redisoperator
      containers:
      - image: quay.io/spotahome/redis-operator:latest
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redisoperator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redisoperator
subjects:
- kind: ServiceAccount
  name: redisoperator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisoperator
rules:
- apiGroups:
    - databases.spotahome.com
  resources:
    - redisfailovers
  verbs:
    - "*"
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - events
    - configmaps
  verbs:
    - "*"
- apiGroups:
    - apps
  resources:
    - deployments
    - statefulsets
  verbs:
    - "*"
- apiGroups:
    - policy
  resources:
    - poddisruptionbudgets
  verbs:
    - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redisoperator
```

Thanks in advance
