### ISSUE TITLE
Custom config does not work

### ISSUE THREAD

**Issue by xiaozhongliu** [spotahome/redis-operator#175]
### Expected behaviour
Custom config works.

### Actual behaviour
Custom config does not work.

### Steps to reproduce the behaviour
It looks like the custom config below is ignored:
```yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
  namespace: data
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    customConfig:
      - 'port 7000'
      - 'cluster-enabled yes'
      - 'cluster-config-file nodes.conf'
      - 'cluster-node-timeout 5000'
      - 'appendonly yes'
```
