### ISSUE TITLE
Sentinel node failed to bootstrap

### ISSUE THREAD

**Issue by bluven** [spotahome/redis-operator#176]
### Expected behaviour

Sentinel node bootstraps successfully.

### Actual behaviour

Sentinel node failed to bootstrap because something happened to container sentinel-config-copy:

```
Init Containers:
  sentinel-config-copy:
    Container ID:  docker://73bebf78ef374d294221314c5ef79f42646dadc04cd41b1efa8439afca2b0012
    Image:         redis:5.0-alpine
    Image ID:      docker-pullable://redis@sha256:7d2a7f4444bf4728f79360cc7b36b9537ab73782284e90d3e07f6098ffe92b71
    Port:          <none>
    Host Port:     <none>
    Command:
      cp
      /redis/sentinel.conf
      /redis-writable/sentinel.conf
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 16777216 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/kubepods/podccc5c555-a222-11e9-b5a0-fa163ea41f47/73bebf78ef374d294221314c5ef79f42646dadc04cd41b1efa8439afca2b0012/memory.limit_in_bytes: device or resource busy\\\"\"": unknown
      Exit Code:    128
      Started:      Tue, 09 Jul 2019 16:23:20 +0800
      Finished:     Tue, 09 Jul 2019 16:23:20 +0800
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     10m
      memory:  16Mi
    Requests:
      cpu:        10m
      memory:     16Mi
    Environment:  <none>
    Mounts:
      /redis from sentinel-config (rw)
      /redis-writable from sentinel-config-writable (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dndgt (ro)
```

### Steps to reproduce the behaviour

`kubectl apply -f basic.yaml`

basic.yaml
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
      exporter:
        enabled: true
```
### Environment

How are the pieces configured?
* Redis Operator version: 1.0.0
* Kubernetes version:v1.12.2
