### ISSUE TITLE
Persisted Storage setting does not correctly set the securityContext on GKE

### ISSUE THREAD

**Issue by theclive** [spotahome/redis-operator#188]
### Expected behaviour

When following the procedure in the README.md to add Persisted storage, we expected persisted storage to work as described.

However, after some investigation, we realised that the `fsGroup` security context was not being set.  Therefore the Persisted Storage was being mounted as `root` with permissions `drwxr-xr-x`, and Redis was running under user `redis`.  We solved this by adding the following to the redis config in the below example:

```
    redis:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
```

### Actual behaviour

We received the following error in the Redis logs prior to defining our own `securityContext`:
```
Error reply to PING from master: '-MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-wri'
```

### Steps to reproduce the behaviour

Use the following RedisFailover config on a standard Google Container Engine cluster:
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  labels:
    project: myproject
    name: redis-ha
    env: production
  name: redis-ha-prod
spec:
  sentinel:
    replicas: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: sentinel
                  app.kubernetes.io/name: redis-ha-prod
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: redis
                  app.kubernetes.io/name: redis-ha-prod
              topologyKey: kubernetes.io/hostname
    storage:
      persistentVolumeClaim:
        metadata:
          name: redis-ha-prod-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
```

### Environment

How are the pieces configured?
* Redis Operator version: v1.0.0-rc.1
* Kubernetes version: 1.13.7-gke.24
* Kubernetes configuration used: Defined by Google Container Engine

### Logs

Log Level: Notice

```
I 2019-10-01T00:01:39.909718270Z 1:S 01 Oct 2019 00:01:39.909 # Error reply to PING from master: '-MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-wri'
```
