### ISSUE TITLE
question: enabling redis auth

### ISSUE THREAD

**Issue by lummie** [spotahome/redis-operator#201]
### Expected behaviour

What do you want to achieve?
Enable redis auth and connect from a client

### Actual behaviour
Client returns: `ERR Client sent AUTH, but no password is set`

### Steps to reproduce the behaviour

Following the example from the readme section : `Enabling redis auth`
```
echo -n "pass" > password
kubectl create secret generic redis-auth --from-file=password

## example config
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 1
  auth:
    secretPath: secret
```
The above example creates a secret called `redis-auth` with a key of `password` and the value set to the password.

What I don't understand is the relationship between `secretPath` and it's value of `secret`.
Should this actually be `redis-auth`?
If the operator is hardcoded to use the secret  name `redis-auth` does that then mean I cannot have two instances of the operator running with different authentication?

Any clarification would be good.
