### ISSUE TITLE
when master set password，slave can't sync with master

### ISSUE THREAD

**Issue by luobaolong** [spotahome/redis-operator#217]
### Actual behaviour

When I set password to redis with using secret redis-auth config，slave can't sync with master
### Logs

1:S 27 Dec 2019 10:23:13.949 * MASTER <-> REPLICA sync started
1:S 27 Dec 2019 10:23:13.949 * Non blocking connect for SYNC fired the event.
1:S 27 Dec 2019 10:23:13.950 * Master replied to PING, replication can continue...
1:S 27 Dec 2019 10:23:13.950 * Partial resynchronization not possible (no cached master)
1:S 27 Dec 2019 10:23:13.950 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master

**Comment by chusAlvarez** [comment]
The relaunch afte an update is progressive, so no data is lost:
-First the slaves are updated, one by one
-Only after all slaves are synced, the master is updated too.

So seems the new slaves are launch with the new password, but the master is working still with the old one.  If you are not afraid to loose data, you can manually delete all pods so they are relaunched with the new values.

But if you need be sure there is no data lost and the service is not interrupted, the solution is more complex as will need change first the password in the master and then the slaves, and this functionality is not supported currently by the redis-operator. You will need scale to 0 redis-operator and update the configuration manually

**Comment by luobaolong** [comment]
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test000
  namespace: redis
spec:
  redis:
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--protected-mode"
      - "no"
    customConfig:
      - maxclients 100
      - maxmemory 1G
      - hz 50
      - timeout 60
      - tcp-keepalive 60
      - client-output-buffer-limit normal 0 0 0
      - client-output-buffer-limit slave 1000000000 1000000000 0
      - client-output-buffer-limit pubsub 33554432 8388608 60
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v0.33.0
    image: redis:4.0-alpine
    imagePullPolicy: IfNotPresent
    replicas: 3
    resources:
      limits:
        cpu: 1500m
        memory: 2.00Gi
      requests:
        cpu: 100m
        memory: 1.50Gi
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    storage:
      persistentVolumeClaim:
        metadata:
          name: redis-persistent-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: rbd
  sentinel:
    command:
      - "redis-server"
      - "/redis/sentinel.conf"
      - "--sentinel"
      - "--protected-mode"
      - "no"
    customConfig:
      - down-after-milliseconds 2000
      - failover-timeout 3000
    exporter: 
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
    image: redis:4.0-alpine
    imagePullPolicy: IfNotPresent
    replicas: 3
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
  auth:
    secretPath: redis-auth

This is my config, when I apply them, all is slave. 
And the redis info:
# Replication
role:slave
master_host:127.0.0.1
master_port:6379
master_link_status:down

And the log:
1:S 30 Dec 12:36:53.191 * Connecting to MASTER 127.0.0.1:6379
1:S 30 Dec 12:36:53.192 * MASTER <-> SLAVE sync started
1:S 30 Dec 12:36:53.192 * Non blocking connect for SYNC fired the event.
1:S 30 Dec 12:36:53.192 * Master replied to PING, replication can continue...
1:S 30 Dec 12:36:53.192 * Partial resynchronization not possible (no cached master)
1:S 30 Dec 12:36:53.192 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master

**Comment by daniel-sullivan** [comment]
Also experiencing this issue on a completely clean deploy.

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
  auth:
    secretPath: redis-auth
  redis:
    replicas: 3
    storage:
      persistentVolumeClaim:
        metadata:
          name: redis-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
```

```
apiVersion: v1
data:
  password: <snip>
kind: Secret
metadata:
  name: redis-auth
type: Opaque
```

**Comment by hoffoo** [comment]
@daniel-sullivan your config looks correct, are you sure its totally clean deploy? can you paste the logs that you see in the sentinels?

**Comment by tuchinsky** [comment]
@hoffoo 

faced the same problem

```
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  hardAntiAffinity: true
  sentinel:
    replicas: 3
    image: redis:5.0-alpine
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    customConfig: []
  auth:
    secretPath: redis-auth
  redis:
    replicas: 3
    image: redis:5.0-alpine
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 600Mi
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
    storage:
      emptyDir: {}
    customConfig:
      - "maxmemory 512MB"
      - "maxmemory-policy allkeys-lru"
```

```
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
data:
  password: cmVkaXMK
type: Opaque
```

rfr logs:
```
1:S 20 Feb 2020 20:29:28.180 * Connecting to MASTER 127.0.0.1:6379
1:S 20 Feb 2020 20:29:28.180 * MASTER <-> REPLICA sync started
1:S 20 Feb 2020 20:29:28.180 * Non blocking connect for SYNC fired the event.
1:S 20 Feb 2020 20:29:28.180 * Master replied to PING, replication can continue...
1:S 20 Feb 2020 20:29:28.180 * Partial resynchronization not possible (no cached master)
1:S 20 Feb 2020 20:29:28.180 * Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
```

totally clean deploy

rfs logs:
```
1:X 20 Feb 2020 20:23:16.703 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 20 Feb 2020 20:23:16.703 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 20 Feb 2020 20:23:16.703 # Configuration loaded
1:X 20 Feb 2020 20:23:16.704 * Running mode=sentinel, port=26379.
1:X 20 Feb 2020 20:23:16.704 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 20 Feb 2020 20:23:16.707 # Sentinel ID is 665d433340da502d766b5c623ea789d87bd9d34c
1:X 20 Feb 2020 20:23:16.707 # +monitor master mymaster 127.0.0.1 6379 quorum 2
1:X 20 Feb 2020 20:23:17.722 # +sdown master mymaster 127.0.0.1 6379
```
