### ISSUE TITLE
Custom Annotations for Services

### ISSUE THREAD

**Issue by alecjacobs5401** [spotahome/redis-operator#219]
### Expected behaviour

Custom annotations for the Redis Sentinel Service should be applied to the respective service based on the `RedisFailover` yml configuration.

### Actual behaviour

Annotations cannot be applied from the `RedisFailover` yml configuration

### Steps to reproduce the behaviour

1. Define `RedisFailover` yml configuration as follows
```yml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    serviceAnnotations:
      example: annotation
```
2. Apply configuration
3. `kubectl describe service <sentinel-service>
4. See Annotations.

### Environment
**N/A - Feature Request**

### Logs
**N/A - Feature Request**

This pretty much should have gone hand in hand with #166 (I think it was supposed to but was forgotten - my bad!). I'm happy to run with the implementation again,.
