### ISSUE TITLE
custom annotations for services are not considered

### ISSUE THREAD

**Issue by ks888sk** [spotahome/redis-operator#224]
### Expected behaviour

When I apply the yaml file below to create the redis failover, custom annotations for services are not considered.

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    serviceAnnotations:
      key: "value"
```

I expect my custom annotation is included in the output below.

```
$ kubectl describe services rfr-redisfailover
...
Annotations:       prometheus.io/path: /metrics
                   prometheus.io/port: http
                   prometheus.io/scrape: true
...
```

I think the `serviceAnnotations` option is added recently ( https://github.com/spotahome/redis-operator/pull/220 ) , but the version which contains the change is not released yet.

### Actual behaviour

The custom annotation is not considered.

### Steps to reproduce the behaviour

```
kubectl apply -f [the yaml above]
kubectl describe services rfr-redisfailover
```

### Environment

How are the pieces configured?
* Redis Operator version

v1.0.0-rc.1

* Kubernetes version

1.14.9

* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
