### ISSUE TITLE
THP and somaxconn fix

### ISSUE THREAD

**Issue by devlounge** [spotahome/redis-operator#23]
Hi,

Could you add this on the StatefulSet to prevent redis warning about max conn and transparent huge pages?

```
      initContainers:
      - name: fix-somaxconn
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w net.core.somaxconn=65535
        securityContext:
          privileged: true
      - name: disable-thp
        image: busybox
        volumeMounts:
          - name: host-sys
            mountPath: /host-sys
        command:
        - /bin/sh
        - -c
        - |
          echo never >/host-sys/kernel/mm/transparent_hugepage/enabled
```
