### ISSUE TITLE
Add support for health checks

### ISSUE THREAD

**Issue by logdnalf** [spotahome/redis-operator#232]
### Expected behaviour

Pods deployed by the Redis Operator should implement some basic `livenessProbe` and `readinessProbe` support. A default should be provided, but it should be possible to override it.

### Actual behaviour

Pods deployed the Redis Operator do not use any form of probes.

### Environment

How are the pieces configured?
* Redis Operator version: latest
* Kubernetes version: 1.13+
* Kubernetes configuration used: RBAC

**Comment by logdnalf** [comment]
Example of Redis probes:

```
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) -p 6371 ping"
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) -p 6371 ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
```
