### ISSUE TITLE
Custom command does not work

### ISSUE THREAD

**Issue by simonhou** [spotahome/redis-operator#250]
### Expected behaviour

Use custom command , --port xxxx , to modify port number

### Actual behaviour

The replica still listens on 6379 port as follows:
![image](https://user-images.githubusercontent.com/1290401/77058744-ced04c80-6a10-11ea-98b5-a3d2044d0a8e.png)

### Environment

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test
spec:
  sentinel:
    hostNetwork: true
    replicas: 3
    command:
      - "redis-server"
      - "/redis/sentinel.conf"
      - "--sentinel"
      - "--port"
      - "17700"
      - "--protected-mode"
      - "no"
    customConfig:
      - "down-after-milliseconds 2000"
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    hostNetwork: true
    replicas: 3
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--port"
      - "16379"
    customConfig:
      - "maxclients 100"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
```
