### ISSUE TITLE
Create service for redis sentinel metrics

### ISSUE THREAD

**Issue by minac** [spotahome/redis-operator#251]
### Expected behaviour

Nothing is broken, this is an enhancement request.
I would like for the operator to create a service to expose the sentinel Prometheus metrics in the same way it does for Redis itself.

### Actual behaviour

When the exporter for Redis is enabled in the configuration of the `Failover`, the operator creates a service that exposes the exporter metrics port. However, the same does not happen when we enable the exporter for the sentinel. This issue is to ask for that to happen, while at the same time ask for a better name to be given to the metrics-exposing service for Redis.

### Steps to reproduce the behaviour

I ended up creating a service for sentinel metrics myself and then coupling it with a ServiceMonitor from the Prometheus Operator. It would be nice if this was all encapsulated in the operator.

### Environment

* Redis Operator version: quay.io/spotahome/redis-operator:v1.0.0
* Kubernetes version: v1.13.12
* Kubernetes configuration used (eg: Is RBAC active?) RBAC is active

### Logs

N/A

**Comment by alphashuro-br** [comment]
@minac can you please share details of how you did this? I am currently trying to do the same thing

**Comment by minac** [comment]
Sure @alphashuro-br!

I created a service to expose the metrics like this:
```
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-redis-sentinel-metrics
  labels:
    app: myapp
    component: sentinel
    env: myenv
  namespace: mynamespace
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9355
  selector:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/name: myapp
    app.kubernetes.io/part-of: redis-failover
  type: ClusterIP
```

And then using the Prometheus operator, a ServiceMonitor like this:
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-redis-sentinel-metrics
  labels:
    app: myapp
    component: sentinel
    env: myenv
  namespace: mynamespace
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
      - mynamespace
  selector:
    matchLabels:
      app: myapp
      component: sentinel
      env: myenv
```

I hope this gets included into the operator since there is already a service for the `redis` metrics, but in the meanwhile it works.
