### ISSUE TITLE
Sentinel service as LoadBalancer Type

### ISSUE THREAD

**Issue by Szuster6** [spotahome/redis-operator#260]
### Expected behaviour

Redisfailover service should be LoadBalancer type, to work outside the cluster, also with static IP as variable. It's rather the request for custom modifications Service Type with values.

```
kubectl get svc
rfs-redisfailover      LoadBalancer   10.129.0.149   10.32.93.4    26379:31307/TCP              3d4h
```

service spec config:
```
spec:
  clusterIP: 10.129.0.149
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.32.93.4
  ports:
  - name: sentinel
    nodePort: 31307
    port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/name: redisfailover
    app.kubernetes.io/part-of: redis-failover
  sessionAffinity: None
  type: LoadBalancer
```
had to add plugin Metallb in kubernetes for external IP broadcast

### Actual behaviour

Redisfailover service can only be ClusterIP type

```
kubectl get svc
rfs-redisfailover           ClusterIP      10.129.0.133   <none>        26379/TCP                    2d4h
```

service spec config:
```
spec:
  clusterIP: 10.129.0.149
  externalTrafficPolicy: Cluster
  ports:
  - name: sentinel
    nodePort: 31307
    port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/name: redisfailover
    app.kubernetes.io/part-of: redis-failover
  sessionAffinity: None
  type: ClusterIP
```
