### ISSUE TITLE
Default shutdown.sh cannot reach Sentinel

### ISSUE THREAD

**Issue by leejones** [spotahome/redis-operator#261]
Thank you for providing this operator! I ran into an issue that I hope can be resolved.

### Expected behaviour

The [default `shutdown.sh` script](https://github.com/spotahome/redis-operator/blob/11131c841062ddb0b7ea53e98c220ea1e6dc185b/operator/redisfailover/service/generator.go#L165-L169) varies the Sentinel service name based on the name of the `RedisFailover`.

### Actual behaviour

The script expects the Sentinel service name to be `rfs-redis` so it only works if `RedisFailover` is named `redis`. The script won't initiate the failover when the `RedisFailover` is named anything else.

### Steps to reproduce the behaviour

1. Create a `RedisFailover` with any name other than `redis`, for example:
```yaml
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 2
```
2. `kubectl exec` into a Redis pod and call the shutdown script in the same way that the `preStop` lifecycle hook calls it:
```
$> kubectl exec -it rfr-redisfailover-0 -- /bin/sh /redis-shutdown/shutdown.sh
Could not connect to Redis at -p:6379: Name does not resolve
OK
sh: 10.66.10.71: unknown operand
```

The `redis-cli save` works since it's using `localhost`, but the calls to Sentinel fail. The errors are because the Sentinel service ENV vars the script is using are nil, for example:

```
/data $ echo $RFS_REDIS_SERVICE_HOST
# no output
```

### Environment

* Redis Operator version: `v1.0.0`
* Kubernetes version: `v1.15.9`
