### ISSUE TITLE
Support Threaded I/O in Redis 6

### ISSUE THREAD

**Issue by nishaad78** [spotahome/redis-operator#271]
Config for `io-threads` cannot be changed during runtime, and hence doesn't take effect with `customConfig` spec in RedisFailover resource.
Is there any way of enabling this using this operator?

**Comment by srinathhs** [comment]
There is a `command:` section which can be used to inject args. 

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-test
spec:
  sentinel:
    <...>
  redis:
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - <YOUR_CUSTOM_ARG_HERE>
```
