### ISSUE TITLE
Allow changing redis-exporter resources in RedisFailover object

### ISSUE THREAD

**Issue by minac** [spotahome/redis-operator#273]
### Expected behaviour

I'd like to be able to set the resources (requests and limits) for `redis-exporter` in the RedisFailover object

### Actual behaviour

Adding the resources stanza like this does not change the default resources:

```
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.5.2-alpine
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 25m
          memory: 100Mi
```

### Steps to reproduce the behaviour

See above.

### Environment

How are the pieces configured?
* Redis Operator version: 1.0.0
* Kubernetes version: 1.16
* Kubernetes configuration used (eg: Is RBAC active?): RBAC yes

### Logs

N/A
