### ISSUE TITLE
Issue to increase memory / replicas / ...

### ISSUE THREAD

**Issue by Dudesons** [spotahome/redis-operator#278]
### Expected behaviour

What do you want to achieve?

I want to increase the memory, so I upgrade the value in the manifest.

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?
The operator is in an error loop with the following log:
```
time="2020-07-01T07:58:46Z" level=error msg="Error processing default/redis-operator-redis-redisoperatordeploy: StatefulSet.apps \"rfr-redis-operator-redis-redisoperatordeploy\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden" controller=redisfailover operator=redis-operator src="generic.go:224"
```

I tried also with replicas only and it doesn't work

### Steps to reproduce the behaviour

Boot a new cluster, after that try to change the memory param.
The manifest:
```yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-operator-redis-redisoperatordeploy
  namespace: default
spec:
  auth:
    secretPath: redis-auth
  redis:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: workloadType
              operator: In
              values:
              - general-purpose
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: kubernetes.io/hostname
          weight: 100
    customConfig:
    - maxclients 10000
    - tcp-keepalive 60
    - appendonly yes
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
    image: redis:5.0-alpine
    replicas: 3
    resources:
      limits:
        cpu: 1500m
        memory: 1024Mi
      requests:
        cpu: 1500m
        memory: 1024Mi
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    storage:
      persistentVolumeClaim:
        metadata:
          name: redis-operator-redis-redisoperatordeploy
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
  sentinel:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: workloadType
              operator: In
              values:
              - general-purpose
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: kubernetes.io/hostname
          weight: 90
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
    image: redis:5.0-alpine
    replicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
```

### Environment

How are the pieces configured?
* Redis Operator version: quay.io/spotahome/redis-operator:latest (I don't know how can I find the right version), the operator was deployed this week
* Kubernetes version: 1.16.8
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

I don't find where to add the debug flag in the chart
