### ISSUE TITLE
exposed the parameters of Service (type) generated?

### ISSUE THREAD

**Issue by brucemei** [spotahome/redis-operator#285]
the hard-code when service create, can exposed the **Type** & **ClusterIP** & **NodePort**?

https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go
``` yaml
Spec: corev1.ServiceSpec{
			Type:      corev1.ServiceTypeClusterIP,
			ClusterIP: corev1.ClusterIPNone,
			Ports: []corev1.ServicePort{
				{
					Port:     exporterPort,
					Protocol: corev1.ProtocolTCP,
					Name:     exporterPortName,
				},
			},
			Selector: selectorLabels,
		},
```
Hard coding
