### ISSUE TITLE
Openshift 3.11 - "oc get all" gives "redisfailovers.databases.spotahome.com  cannot list" error

### ISSUE THREAD

**Issue by dejwsz** [spotahome/redis-operator#293]
### Expected behaviour

Do not see such error for a regular user

### Actual behaviour
in some project when I as a regular user (so not cluster admin) do:
oc get all

at the end I have such error:
Error from server (Forbidden): redisfailovers.databases.spotahome.com is forbidden: User "testuser" cannot list redisfailovers.databases.spotahome.com in the namespace "testprj": no RBAC policy matched

### Steps to reproduce the behaviour

Just install the operator and log in as a regular user and try to do 'oc get all'

### Environment

* Redis Operator version: v1.0.0.
* Kubernetes version: Openshift 3.11
* Kubernetes configuration used (eg: Is RBAC active?): Openshift 3.11 so it is

**Comment by dejwsz** [comment]
Ok I found it, there is a need to add aggregate clusteroles to extend the default view, edit and admin clusterroles. Like:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-to-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
   - databases.spotahome.com
  resources:
  - redisfailovers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-to-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
   - databases.spotahome.com
  resources:
  - redisfailovers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-to-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
   - databases.spotahome.com
  resources:
  - redisfailovers
  verbs:
  - get
  - list
  - watch

```
