### ISSUE TITLE
Enable min-replicas-to-write by default

### ISSUE THREAD

**Issue by baurmatt** [spotahome/redis-operator#299]
### Expected behaviour

Writes to the master node should be prohibited as fast a possible on failover. This ensure less data is lost due to Redis nature of asynchron replication. See https://redis.io/topics/sentinel#example-2-basic-setup-with-three-boxes and https://redis.io/topics/replication#allow-writes-only-with-n-attached-replicas

I think it would be beneficial for every user if the cluster would at least have `min-replicas-to-write = 1` if replicas > 2.

### Actual behaviour

min-replicas-to-write is currently not configured.

### Steps to reproduce the behaviour

Setup a cluster and check config setting `min-replicas-to-write` 

### Environment

How are the pieces configured?
* Redis Operator version: 1.0.0
* Kubernetes version: 1.18.13
* Kubernetes configuration used (eg: Is RBAC active?) `--set rbac.install=true --set monitoring.enabled=true`

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
  redis:
    replicas: 3
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
```

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
