### ISSUE TITLE
PriorityClass support

### ISSUE THREAD

**Issue by khamadiev** [spotahome/redis-operator#306]
Hello, is there any chance of priority class support in custom resource of redis operator?
I see the [commit](https://github.com/spotahome/redis-operator/commit/d3a263388d792397bdbba74062a7fb6078a7d1dd) that added it about 7 months ago, but the latest release of operator was a lot earlier.
Could you publish a new release, please?

**Comment by ese** [comment]
It's implemented in the last release v1.1.0-rc.1:

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    priorityClassName: system-cluster-critical
    replicas: 3
  redis:
    priorityClassName: system-cluster-critical
    replicas: 3
```
