### ISSUE TITLE
error syncing sentinel deployment 

### ISSUE THREAD

**Issue by arnaud-mey** [spotahome/redis-operator#328]
### Actual behaviour

I'm seeing the following error on the controller-manager for all redis clusters:

`I1001 06:49:47.036248       1 deployment_controller.go:490] "Error syncing deployment" deployment="loki/rfs-redis-loki" err="Operation cannot be fulfilled on deployments.apps \"rfs-redis-loki\": the object has been modified; please apply your changes to the latest version and try again"`

### Steps to reproduce the behaviour

Create a redis cluster with the following CR:

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-loki
spec:
  sentinel:
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
    replicas: 3
    image: redis:6.2.3-alpine
  redis:
    replicas: 3
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 100m
        memory: 1Gi
    image: redis:6.2.5-alpine
    customConfig:
      - "maxmemory 900mb"
      - "maxmemory-policy allkeys-lfu"
    podAnnotations:
      injector.tumblr.com/request: "prometheus-redis-exporter:v1"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "failure-domain.beta.kubernetes.io/zone"
            labelSelector:
              matchExpressions:
                - key: redisfailovers.databases.spotahome.com/name
                  operator: In
                  values:
                    - redis-loki
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - redis
```

### Environment

How are the pieces configured?
* Redis Operator version: v1.0.0
* Kubernetes version: v1.21.4
