### ISSUE TITLE
Cannot set seccompProfile in securityContext

### ISSUE THREAD

**Issue by haslersn** [spotahome/redis-operator#338]
When deploying a RedisFailover with seccompProfile like

```yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  redis:
    replicas: 3
    securityContext:
      seccompProfile:
        type: RuntimeDefault
```

then the Pods are created with an empty securityContext.

### Expected behaviour

seccompProfile should be supported. Ideally, the default securityContext should already set the seccompProfile to `{type: RuntimeDefault}` in order to be compatible with the Restricted policy of [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/).

### Environment

How are the pieces configured?
* Redis Operator version: 1.0.0
* Kubernetes version: 1.19
