### ISSUE TITLE
Upgrade to 1.1.0-rc.2 fails

### ISSUE THREAD

**Issue by n1kk0** [spotahome/redis-operator#357]
### Expected behaviour
Upgrade from 1.0.0 to 1.1.0-rc.2

### Actual behaviour
The new operator fails.

### Steps to reproduce the behaviour
My redisoperator Deployment : 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisoperator
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/name: redisoperator
    app: redisoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisoperator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/name: redisoperator
        app: redisoperator
    spec:
      serviceAccountName: redisoperator
      restartPolicy: Always
      containers:
        - image: quay.io/spotahome/redis-operator:v1.1.0-rc.2
          imagePullPolicy: IfNotPresent
          name: app
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
          - containerPort: 9710
            name: metrics
            protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
```
my redisfailover :
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    image: redis:6.0.15-alpine
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    image: redis:6.0.15-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 1024Mi
      limits:
        cpu: 400m
        memory: 4096Mi
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: redisfailover-persistent-keep-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    command:
      - redis-server
      - /redis/redis.conf
      - --databases
      - "36"
    exporter: 
      enabled: true
      image: oliver006/redis_exporter:v1.33.0-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 200Mi
```

### Environment
I'm on kube 1.18

### Logs
```
time="2022-01-17T20:35:42Z" level=info msg="Listening on :9710 for metrics exposure" src="asm_amd64.s:1581"
time="2022-01-17T20:35:42Z" level=info msg="starting controller" controller-id=redisfailover operator=redisfailover service=kooper.controller src="controller.go:233"
time="2022-01-17T20:35:42Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=myns service=k8s.configMap src="configmap.go:78"
time="2022-01-17T20:35:42Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=myns service=k8s.configMap src="configmap.go:78"
time="2022-01-17T20:35:42Z" level=info msg="configMap updated" configMap=rfr-readiness-redisfailover namespace=myns service=k8s.configMap src="configmap.go:78"
time="2022-01-17T20:35:42Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=myns service=k8s.configMap src="configmap.go:78"
time="2022-01-17T20:35:42Z" level=error msg="error on object processing: the server could not find the requested resource" controller-id=redisfailover object-key=myns/redisfailover operator=redisfailover service=kooper.controller src="controller.go:279"
```
