### ISSUE TITLE
Metrics endpoint returns 404 on latest RC

### ISSUE THREAD

**Issue by erdeerdeerde** [spotahome/redis-operator#367]
### Expected behaviour

A curl of the metrics endpoint returns the metrics.

### Actual behaviour

It returns 404 page not found

### Steps to reproduce the behaviour

deploy the latest rc v1.1.0-rc.3 to kube and try to curl the metrics like so `curl http://10.0.0.18:9710/metrics`

After a downgrade to v1.0.0 it works as expected.

### Environment

How are the pieces configured?
* Redis Operator version: v1.1.0-rc.3
* Kubernetes version: v1.19.4
* Kubernetes configuration used: RBAC active

### Logs

[redis_op_debug_log.txt](https://github.com/spotahome/redis-operator/files/7977646/redis_op_debug_log.txt)

**Comment by ese** [comment]
Thanks, @erdeerdeerde I tried to reproduce and I can't. Could you try with the last release v1.1.0 and provide the resources YAML to try to reproduce it

**Comment by ekeih** [comment]
Seeing the same issue with 1.1.0.

Using the helm chart at https://spotahome.github.io/redis-operator to deploy the operator with the following values:
```
image:
  respository: quay.io/spotahome/redis-operator
  pullPolicy: IfNotPresent
  tag: v1.1.0

monitoring:
  enabled: true
  serviceMonitor: true
```

(I think the v1.1.0 chart did not get published, so I set the 1.1.0 image manually in the values.)

**Comment by erdeerdeerde** [comment]
Hi @ese 
Also does not work with v1.1.0
Our Deployment is as follows:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redisoperator
  name: redisoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisoperator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redisoperator
    spec:
      serviceAccountName: redisoperator
      containers:
        - image: spotahome/redis-operator:v1.1.0
          imagePullPolicy: IfNotPresent
          name: app
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
      restartPolicy: Always
```
