### ISSUE TITLE
Change Redis pods exposed port

### ISSUE THREAD

**Issue by amitde69** [spotahome/redis-operator#370]
### Expected behaviour

Possibility to change the redis listen port.
I might be missing something ? is it possible to do it ?

### Actual behaviour

At the moment it looks like it is not exposed explicitly and I have to change the redis-server command but this doesn't work because then the probes dont work since they are configured for 6379 and probably the sentinel integration breaks as well.

### Steps to reproduce the behaviour

This is my RedisFailover resource
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
  namespace: datalayer
  labels:
    app: rfr-redis
spec:
  sentinel:
    replicas: 1
    image: {{ .Values.global.account }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/redis:5.0-alpine
    imagePullPolicy: Always
  redis:
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--port 7777"
    customConfig:
      - "maxmemory 9gb"
      - "maxmemory-policy allkeys-lru"
    resources:
      limits:
        cpu: "1"
        memory: "10G"
      requests:
        cpu: "1"
        memory: "10G"
    securityContext:
      runAsUser: 1203
      runAsGroup: 1203
      fsGroup: 1203
    image: {{ .Values.global.account }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/redis:5.0-alpine
    imagePullPolicy: Always
    replicas: 1
    exporter:
      enabled: true
      image: {{ .Values.global.account }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/bitnami/redis-exporter:1.9.0
```

### Environment

How are the pieces configured?
* Redis Operator version - v1.0.0
* Kubernetes version - 1.19
