### ISSUE TITLE
Add support for creating PodMonitor or ServiceMonitor

### ISSUE THREAD

**Issue by sagikazarmark** [spotahome/redis-operator#383]
### Expected behaviour

Create PodMonitor/ServiceMonitor object for Redis and Sentinel.

### Actual behaviour

Prometheus exporters are integrated into the RedisFailover CRD, but they still require PodMonitors or ServiceMonitors.

### Proposed solution

Allow creating PodMonitor or ServiceMonitor resources along with exporters. For example:

```yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  redis:
    exporter:
      enabled: true
    monitoring:
      podMonitor:
          enabled: true
  sentinel:
    exporter:
      enabled: true
    monitoring:
      podMonitor:
          enabled: true
```

### Additional details

I'd be happy to draft a PR if you like the idea.
