### ISSUE TITLE
Linear increase in CPU usage over time of operator

### ISSUE THREAD

**Issue by mgrzeszczak** [spotahome/redis-operator#386]
I've noticed that CPU usage of redis-operator is linearly increasing over time, as seen on the graph below:
![image](https://user-images.githubusercontent.com/4957680/156741096-bd1ac179-719c-4ed2-9c95-33ada4121237.png)

Any idea what might be causing it?

My deployment file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-operator
  name: redis-operator
  namespace: redis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: redis-operator
      labels:
        app: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
        - image: quay.io/spotahome/redis-operator:v1.1.0
          imagePullPolicy: IfNotPresent
          name: redis-operator
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always

```
