### ISSUE TITLE
Redis cluster with linkerd

### ISSUE THREAD

**Issue by aceeric** [spotahome/redis-operator#390]
### Expected behaviour

Provision a Redis cluster meshed with linkerd

### Actual behaviour

The redis cluster never seems able to determine master/slave status.

### Steps to reproduce the behaviour

For a baseline, create a **non-meshed** cluster with this manifest:
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-test
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - redis-test
            topologyKey: kubernetes.io/hostname
```

This cluster comes up. Each of the nodes has logging like so:
```
# oOOoO0OoO0Oo Redis is starting oOOoO0OoO0Oo
# Redis version=6.2.6 bits=64 commit=00000000, modified=0, pid=1, just started
# Configuration loaded
* monotonic clock: POSIX clock_gettime
* Running mode=standalone, port=6379
# WARNING: the TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
# Server initialized
* Ready to accept connections
* Connecting to MASTER 1127.0.0.1:6379
* MASTER <-> REPLICA sync started
* Non blocking connect for SYNC fired the event
* Master replide to PING, replication can continue...
* Partial resynchronization not possible (no cached master)
* Master is currently unable to PSYNC but should be in the future: -NOMASTERLINK Can't SYNC while not connected with my master
```
And the last 5 messages will repeat for about 2.5 minutes then eventually:
```
* Synchronization with replica 10.42.215.130:6379 succeeded
* Synchronization with replica 10.42.215.209:6379 succeeded
```
And the logs go quiet.

Same scenario meshed:
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-test
spec:
  sentinel:
    replicas: 3
    podAnnotations:
      linkerd.io/inject: enabled
    ...
  redis:
    replicas: 3
    podAnnotations:
      linkerd.io/inject: enabled
    ...
```
In this scenario, the sync never seems to succeed. So the last 5 messages repeat indefinitely. I'm trying to use this Redis cluster to back a Harbor internal registry. The registry is unstable and I suspect it is because Redis - which Harbor uses for several types of caching - is unstable.

Is there any guidance or exemplars for meshing a Redis cluster this way?

Thanks.

### Environment

* Redis Operator version v1.1.1
* Kubernetes version: 1.21.5
