### ISSUE TITLE
Unable to setup exporter's cpu and memory resources

### ISSUE THREAD

**Issue by kuzm1ch** [spotahome/redis-operator#395]
Step to reproduce:
setup resources for exporter
```
  redis:
    exporter: 
      enabled: true
      image: oliver006/redis_exporter:v1.37.0
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 150Mi 
 ```

Error: 
```
<nil>: Invalid value: "The edited file failed validation": ValidationError(RedisFailover.spec.redis.exporter): unknown field "resources" in com.spotahome.databases.v1.RedisFailover.spec.redis.exporter
```
version: 
appVersion: 1.1.0-rc.1
k8s version: v1.21.3
