### ISSUE TITLE
Feature Request: Istio Support

### ISSUE THREAD

**Issue by heilerich** [spotahome/redis-operator#396]
It would be great if this operator would work out-of-the-box inside istio service meshes. Especially since it does not yet support configuring redis's native transport encryption.

The following three things are necessary to get this running on istio:

1. For some reason redis replicas will announce `127.0.0.1` as their IP when running inside the service mesh. So in order to make failover and synchronization work one must explicitly set the `replica-announce-ip` option.
This can be achieved right now by adding the following command to the resource, but it would be amazing if the operator would support dynamically setting the option to the pod's IP when reconciling the redis settings.
```
command:
- /bin/sh
- -c
- redis-server /redis/redis.conf --replica-announce-ip "$(hostname -i)"
```

2. In order for direct connections to the pod IP to work inside the service mesh, the sidecar proxy must be aware of the ports that services will listen at. This can be achieved by adding a headless service with the correctly named port. Also the `publishNotReadyAddresses` option must be set so the operator can connect to the redis instances while they are not ready yet. 
The operator does not need to make use of this service, it can continue to directly connect via the pods' IP addresses. It is only needed to make the istio mesh aware of the ports so the proxies get the correct configuration.
It would be great if the operator would support adding this service automatically.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: outline-redis: resource-name
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      name: tcp-redis
      port: 6379
      targetPort: 6379
```

5. The same goes for the sentinel deployment.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-headless
spec:
  selector:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/name: outline-redis: resource-name
  clusterIP: None
  ports:
    - protocol: TCP
      port: 26379
      name: tcp-sentinel
      targetPort: 26379
```

These changes could even be applied by default. Explicitly setting the `replica-announce-ip` to the pod IP should not create problems in any environment (it will match the auto detected IP in vanilla environments anyways). And adding the additional headless services should also not create problems for existing deployments. It might even be useful for some people who are not running a service mesh.

I think this would be a great addition and it shouldn't be much work to implement these changes.
