### ISSUE TITLE
Invalid redis sentinel exporter image 

### ISSUE THREAD

**Issue by dantedaemon** [spotahome/redis-operator#409]
### Expected behaviour

Use default redis_sentinel_exporter image.

### Actual behaviour

I get redis_exporter image.

### Steps to reproduce the behaviour

I added 

```
exporter:
  enabled: true
```

for example: 

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    exporter:
      enabled: true
...
```

### Environment

* Redis Operator version - v.1.1.1

A typo in this [commit](https://github.com/spotahome/redis-operator/commit/0e25badcb787c3f93c9f3febc3e10867a2e7d49f#diff-88ba2fcce9ed848afdfc12a51be2bb1c252460192077e83950cd8f2211bf2b68R6)
