### ISSUE TITLE
readinessProbe and livenessProbe fail when AUTH is enforced

### ISSUE THREAD

**Issue by szelenka** [spotahome/redis-operator#417]
### Expected behaviour

Enable AUTH for Redis and Sentinel via :
```yaml
spec:
  auth:
    secretPath: k8s-secret-name
```

#### Issue 1
AUTH is configured on `rfr` pods, but the `livenessProbe` fails because it's not attempting to authenticate:
```yaml
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - redis-cli -h $(hostname) ping
```
The `readinessProbe` doesn't have this issue, as it execute a script from a ConfigMap and the use of `-a $REDIS_PASSWORD}` in #235 . It'd be nice to have a way to modify these probes, similar to how you can modify the `shutdown` script.

#### Issue 2
AUTH is not configured on `rfs` pods, and has similar challenges with `readinessProbe` and `livenessProbe` not attempting to authenticate:
```yaml
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - redis-cli -h $(hostname) -p 26379 ping
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - redis-cli -h $(hostname) -p 26379 ping

```
It'd be nice to have a way to modify these probes, similar to how you can modify the `shutdown` script.

### Steps to reproduce the behaviour

1. Redis docker image which enforces `protected-mode yes`
2. Create a k8s Secret with a `password` field to use as the password for AUTH
3. Enable auth in the RedisFailover CRD

### Environment

* Redis Operator version = 1.1.1
* Kubernetes version = 1.21
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

The Operator is running fine, it's just that it never configures AUTH on the probes for Redis and Sentinel, so k8s will continually think the Pods are not available.
