### ISSUE TITLE
Split-brain multiple master redis from mutiple cluster in same namespace !! 

### ISSUE THREAD

**Issue by raviranjanelastisys** [spotahome/redis-operator#421]
### Expected behaviour

I have recently deployed multiple cluster via "Redisfailover" cluster in the same namespace &&  i don't see any issue and fits our requirement but still correct me if i am wrong . If we can deploy multiple cluster in the same namespace !! ??

I want to know  how operator manages multiple master ( each master of different redis cluster ) in the same namespace !! We facing split-brain issue as multiple masters are getting reported although its false .

I am using below alert-manager config based Prometheus metrics !! 

```
  - alert: RedisMissingMaster
    annotations:
      description: |-
        Redis cluster has no node marked as master
          VALUE = {{ $value }}
          LABELS: {{ $labels }}
      summary: Redis missing master (instance {{ $labels.instance }})
    expr: (count(redis_instance_info{role="master"}) or vector(0)) < 1
    for: 5m
    labels:
      severity: critical
```

### Actual behaviour

What is happening? Are all the pieces created? Can you access to the service?

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version - v1.1.1
* Kubernetes version - v1.22 
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
