### ISSUE TITLE
set password error

### ISSUE THREAD

**Issue by jiuker** [spotahome/redis-operator#427]
### Expected behaviour
I start redis instance.And I set password secret.
What do you want to achieve?
start redis with a password.
### Actual behaviour
Pod status failed!
Readniess always failed.
Readiness probe failed: unespected AUTH failed: WRONGPASS invalid username-password pair or user is disabled.

What is happening? Are all the pieces created? Can you access to the service?
I think it's a bug.
### Steps to reproduce the behaviour
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  password:  mypass
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  auth:
    secretPath: my-secrect
  sentinel:
    replicas: 3
    image: redis:6.2.6
  redis:
    replicas: 3
    image: redis:6.2.6
    exporter: 
      enabled: true
      image: oliver006/redis_exporter:v1.3.5-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
    storage:
      persistentVolumeClaim:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
```

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)
latest
### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
