### ISSUE TITLE
Security Contexts are not merged but overridden

### ISSUE THREAD

**Issue by samof76** [spotahome/redis-operator#469]
### Expected behaviour

Since by default the `securityContext` on is set the following,

```
securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

```

And if apply the a CRD like the following

```
---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: rf0
  namespace: wsc
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 1
    securityContext:
      sysctls:
      - name: net.core.somaxconn
        value: "32000"
      - name: net.ipv4.ip_local_port_range
        value: "8001 64000"
```

Then the pod secuirty context SHOULD be

```
securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    sysctls:
    - name: net.core.somaxconn
      value: "32000"
    - name: net.ipv4.ip_local_port_range
      value: 8001 64000
```

### Actual behaviour

The pod's security context is getting override with this...
```
securityContext:
    sysctls:
    - name: net.core.somaxconn
      value: "32000"
    - name: net.ipv4.ip_local_port_range
      value: 8001 64000

```
