### ISSUE TITLE
Password with `$` or any other special in it fails readiness

### ISSUE THREAD

**Issue by samof76** [spotahome/redis-operator#526]
### Expected behaviour

What do you want to achieve?
I would the setup as redis deployment using the redisfailover CR, with password that accepts special character.

### Actual behaviour

_What is happening? Are all the pieces created? Can you access to the service?_
The readiness for the redis pods fails. But sentinel are able to connect to redis without any issue.

### Steps to reproduce the behaviour

_Describe step by step what you've have done to get to this point_
Try to deploy the following the CR.
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: ps
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: ps
type: Opaque
stringData:
  password: u123886^UzA$$!

---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-ports
  namespace: ps
spec:
  auth:
    secretPath: redis-auth
  redis:
    exporter:
      enabled: true
    port: 12345
    replicas: 3
  sentinel:
    exporter:
      enabled: true
    replicas: 3

```

### Environment

How are the pieces configured?
* Redis Operator version v1.2.2
* Kubernetes version v1.22.7+
* Kubernetes configuration used (eg: Is RBAC active?)
