### ISSUE TITLE
Wrong template monitoring.yaml

### ISSUE THREAD

**Issue by brat002** [spotahome/redis-operator#530]
### Expected behaviour

Enabling of monitoring and ServiceMonitor produces wrong manifest.

### Actual behaviour
```
spec:
  ports:
    - port: 9710
      protocol: TCP
      name: metrics
      targetPort: metrics
  selector:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/instance: redis---
apiVersion: monitoring.coreos.com/v1
```
https://github.com/spotahome/redis-operator/blob/master/charts/redisoperator/templates/monitoring.yaml#L26
### Steps to reproduce the behaviour

```
monitoring:
  # Enable Prometheus PodMonitor to monitor the operator.
  enabled: true
  serviceMonitor: true
  serviceAnnotations: {}
  prometheus:
    name: prometheus-operator-xxx
```
Call helm template.

### Environment

* Redis Operator version is 3.2.4
* Kubernetes version v1.22
