### ISSUE TITLE
Make sentinelExporterPort configurable

### ISSUE THREAD

**Issue by dnugmanov** [spotahome/redis-operator#531]
### Expected behaviour

I can through CRD change sentinelExporterPort (by default 9355) and operator will correct render env spec

### Actual behaviour

If i use env LISTEN_ADDRESS in exporter container, operator incorrect add REDIS_EXPORTER_WEB_LISTEN_ADDRESS env, which is not respected in exporter configuration.

```
        - env:
            - name: LISTEN_ADDRESS
              value: ':9121'
            - name: REDIS_ALIAS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: REDIS_EXPORTER_WEB_LISTEN_ADDRESS
              value: '0.0.0.0:9355'
            - name: REDIS_ADDR
              value: 'redis://localhost:26379'
...
     ports:
        - containerPort: 9355
          name: metrics
          protocol: TCP
```
### Steps to reproduce the behaviour

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test-redis
  namespace: redis-operator
spec:
  auth:
    secretPath: redis-auth
  sentinel:
    image:redis:7.0.5-alpine 
    replicas: 3
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.7.0
      env:
        - name: LISTEN_ADDRESS
          value: ":9121"
```
### Environment

How are the pieces configured?
* Redis Operator version - last
* Kubernetes version - 1.22
* Kubernetes configuration used (eg: Is RBAC active?)
