### ISSUE TITLE
Operator error: services not found

### ISSUE THREAD

**Issue by Braineanear** [spotahome/redis-operator#543]
### Actual behaviour

I found out after days of using the redis failover operator that it logs an error for not finding the rfr-redis service
There are actually two services exists: one for the operator called redis-operator and the other for sentienl called rfs-redis

### Environment

How are the pieces configured?
* Redis Operator version: v1.2.3
* Kubernetes version:  v1.23.11-gke.300
* Kubernetes configuration used 
```
name: redis

sentienl:
  minReplicas: 3
  maxReplicas: 11
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 1Gi

redis:
  password: *****
  minReplicas: 3
  maxReplicas: 11
  storage: 5Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 4Gi
```

### Logs

```
time="2022-12-21T17:45:53Z" level=error msg="Error while getting service rfr-redis in redis namespace : services \"rfr-redis\" not found" src="client.go:160"
time="2022-12-21T17:45:53Z" level=info msg="service updated" namespace=redis service=k8s.service serviceName=rfs-redis src="service.go:99"
time="2022-12-21T17:45:53Z" level=info msg="configMap updated" configMap=rfs-redis namespace=redis service=k8s.configMap src="configmap.go:84"
time="2022-12-21T17:45:53Z" level=info msg="configMap updated" configMap=rfr-s-redis namespace=redis service=k8s.configMap src="configmap.go:84"
time="2022-12-21T17:45:53Z" level=info msg="configMap updated" configMap=rfr-readiness-redis namespace=redis service=k8s.configMap src="configmap.go:84"
time="2022-12-21T17:45:53Z" level=info msg="configMap updated" configMap=rfr-redis namespace=redis service=k8s.configMap src="configmap.go:84"
time="2022-12-21T17:45:53Z" level=info msg="podDisruptionBudget updated" namespace=redis podDisruptionBudget=rfr-redis service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2022-12-21T17:45:53Z" level=info msg="statefulSet updated" namespace=redis service=k8s.statefulSet src="statefulset.go:108" statefulSet=rfr-redis
time="2022-12-21T17:45:53Z" level=info msg="podDisruptionBudget updated" namespace=redis podDisruptionBudget=rfs-redis service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2022-12-21T17:45:53Z" level=info msg="deployment updated" deployment=rfs-redis namespace=redis service=k8s.deployment src="deployment.go:109"
```
