### ISSUE TITLE
RedisFailover with HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by TVGSoft** [spotahome/redis-operator#566]
### Expected behaviour

This is basic deployment for redis failover:
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
```
And I want to use HorizontalPodAutoscaler:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redisfailover
spec:
  scaleTargetRef:
    apiVersion: databases.spotahome.com/v1
    kind: Deployment
    name: redisfailover
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```
Does RedisFailover support this requirement and can you provide an example?
        
### Actual behaviour

Currently, I don't see any example for HorizontalPodAutoscaler with RedisFailover.

### Steps to reproduce the behaviour

Describe step by step what you've have done to get to this point

### Environment

How are the pieces configured?
* Redis Operator version
* Kubernetes version
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
