### ISSUE TITLE
Sentinel misconfigured after availability zone failure

### ISSUE THREAD

**Issue by vramperez** [spotahome/redis-operator#601]
### Expected behaviour

After the failure of an availability zone where the redis master was located, after the failover process, all the sentinels should have the new redis master correctly configured.

### Actual behaviour

The new sentinel pods deployed in the healthy availability zones as a result of terminating the sentinel pods in the failed availability zone have the redis master misconfigured to 127.0.0.1.

### Steps to reproduce the behaviour

Cluster of k8s consisting of 1 master and 3 workers. Each worker in a different availability zone:
- worker1: zone1
- worker2: zone2
- worker3: zone3

Redis deployment consisting of:
- 1 replica of redis-operator
- 3 redis replicas (1 for each zone/worker)
- 3 sentinel replicas (1 for each zone/worker)

![Screenshot from 2023-05-16 11-35-32](https://github.com/spotahome/redis-operator/assets/16591014/493dd73f-7b3a-4bc7-a6c3-8a5e0fdd213c)

Simulate the downtime of the availability zone in which the redis master is located (e.g. shut down worker2 because the master is `rfr-redis-0`).

After the failover process, as there is still a quorum, a new master is elected, and the operation at Redis level is as expected.

![Screenshot from 2023-05-16 11-43-00](https://github.com/spotahome/redis-operator/assets/16591014/1300c10f-51bb-434f-9d60-20e2f4b43df3)

However, the new sentinel that is deployed, as a consequence of losing a sentinel in the downed zone, has the master misconfigured as 127.0.0.1, instead of 10.42.76.3.
```
k exec -it rfs-redis-6c5758686f-bmbf2 -- redis-cli -p 26379
Defaulted container "sentinel" out of: sentinel, sentinel-config-copy (init)
127.0.0.1:26379> sentinel get-master-addr-by-name mymaster
1) "127.0.0.1"
2) "6379"
```
Reading other issues, I understand that this Sentinel has as master 127.0.0.1 as it is the initial configuration. The problem then is in the redis-operator, which does not configure the master correctly in this sentinel (I think because it detects that the previous master is down and does nothing else). 

```
time="2023-05-16T09:36:39Z" level=error msg="Get redis info failed, maybe this node is not ready, pod ip: 10.42.244.15" src="checker.go:113"
time="2023-05-16T09:36:52Z" level=error msg="Get redis info failed, maybe this node is not ready, pod ip: 10.42.244.15" src="checker.go:189"
time="2023-05-16T09:36:52Z" level=info msg="Update pod label, namespace: internal-dev-ci, pod name: rfr-redis-0, labels: map[redisfailovers-role:slave]" service=k8s.pod src="check.go:101"
time="2023-05-16T09:37:04Z" level=error msg="error while getting masterIP : Failed to get info replication while querying redis instance 10.42.244.15" src="check.go:130"
time="2023-05-16T09:37:04Z" level=error msg="Get slave of master failed, maybe this node is not ready, pod ip: 10.42.244.15" src="checker.go:194"
time="2023-05-16T09:37:04Z" level=warning msg="Slave not associated to master: dial tcp 10.42.244.15:6379: connect: network is unreachable" namespace=internal-dev-ci redisfailover=redis src="handler.go:79"
time="2023-05-16T09:37:04Z" level=info msg="Making pod rfr-redis-0 slave of 10.42.76.3" namespace=internal-dev-ci redisfailover=redis service=redis.healer src="checker.go:198"
```

**Is this a design decision of the redis-operator (if it cannot contact a replica, it does nothing else), or is it a bug in the redis-operator?**

Although the redis cluster still works correctly, if you use the sentinel service to ask for the master, sometimes it gives you the correct IP of the master, and sometimes it returns 127.0.0.1, depending on which sentinel endpoint responds:
```
k exec -it rfr-redis-2 -- redis-cli -h rfs-redis -p 26379 
rfs-redis:26379> sentinel get-master-addr-by-name mymaster
1) "127.0.0.1"
2) "6379"

k exec -it rfr-redis-2 -- redis-cli -h rfs-redis -p 26379
rfs-redis:26379> sentinel get-master-addr-by-name mymaster
1) "10.42.76.3"
2) "6379"
```
**NOTE:** For the time being, I have prevented this behaviour by configuring a `TopologySpreadConstraint` with `DoNotSchedule` in sentinel, to prevent new sentinel pods from being deployed when an availability zone is lost. 

### Environment

* Redis Operator version: 3.2.8
* App version: 1.2.4
* Kubernetes version: 1.21
* Chart values: default values
* Cluster:
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
  namespace: internal-dev-ci
  labels:
    role: dbserver
    type: redis
spec:
  sentinel:
    image: docker.io/library/redis:6.2.6-alpine
    replicas: 3
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: sentinel
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: sentinel
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
    resources: {}
  redis:
    image: docker.io/library/redis:6.2.6-alpine
    replicas: 3
    customConfig:
    - "appendonly yes"
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: redis
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: redis
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: redis-data
        spec:
          selector:
            matchLabels:
              app: redis-data
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    resources: {}
```

### Logs
[new_sentinel.txt](https://github.com/spotahome/redis-operator/files/11486523/new_sentinel.txt)
[redis-operator.txt](https://github.com/spotahome/redis-operator/files/11486524/redis-operator.txt)
[sentinel1.txt](https://github.com/spotahome/redis-operator/files/11486525/sentinel1.txt)
[sentinel2.txt](https://github.com/spotahome/redis-operator/files/11486526/sentinel2.txt)
