### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by tamis-laan** [spotahome/redis-operator#635]
Problems connecting to redis, might be related to operator:
https://github.com/redis/ioredis/issues/1781

I'm trying to connect to the redis cluster through the service that routes traffic to the sentinels. Here is the deployment spec:

``` yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 100m
        memory: 40Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
      limits:
        cpu: 100m
        memory: 40Mi
```
