### ISSUE TITLE
CRDs not being installed on chart version v3.3.0

### ISSUE THREAD

**Issue by zumic96** [spotahome/redis-operator#645]
### Expected behaviour

I wanted to install latest version of chart on my clusters.

### Actual behaviour

Installation failed with unmarshal error when installing CRD.
```
Error: failed to install CRD crds/databases.spotahome.com_redisfailovers.yaml: error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
```

### Steps to reproduce the behaviour

Run helmfile installation of chart.

helmfile.yaml
```
repositories:
  - name: redis-operator
    url: https://spotahome.github.io/redis-operator

releases:
  - name: redis-operator
    namespace: redis-operator
    chart: redis-operator/redis-operator
    values:
      - values.yaml
```

values.yaml
```
replicas: 2
```

command used
```
helmfile apply -f helmfile.yaml
```

As a workaround added version to helmfile release config
```
repositories:
  - name: redis-operator
    url: https://spotahome.github.io/redis-operator

releases:
  - name: redis-operator
    namespace: redis-operator
    chart: redis-operator/redis-operator
    version: 3.2.9
    values:
      - values.yaml
```

### Environment

How are the pieces configured?
* Redis Operator version 1.3.0
* Kubernetes version 1.26

### Logs

Please, add the debugging logs. In order to be able to gather them, add `-debug` flag when running the operator.
