### ISSUE TITLE
v1.3.0-rc1 image is incorrect in Kustomize

### ISSUE THREAD

**Issue by sagikazarmark** [spotahome/redis-operator#650]
### Expected behaviour

Installing v1.3.0-rc1 with kustomize succeeds

### Actual behaviour

Installation fails with image pull error. The kustomize manifest tries to pull `quay.io/spotahome/redis-operator:v1.3.0` which obviously does not exist.

### Steps to reproduce the behaviour

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/spotahome/redis-operator/manifests/kustomize/overlays/minimal?ref=v1.3.0-rc1

```

The problematic bit: https://github.com/spotahome/redis-operator/blob/master/manifests/kustomize/components/version/kustomization.yaml#L10

### Environment

How are the pieces configured?
* Redis Operator version: v1.3.0-rc1
* Kubernetes version: 1.27
* Kubernetes configuration used (eg: Is RBAC active?)

### Logs

Logs are irrelevant here

### Workaround

The issue can be worked around with the following kustomize config:

```yaml
images:
  - name: quay.io/spotahome/redis-operator
    newTag: v1.3.0-rc1
```
