### ISSUE TITLE
disablePodDisruptionBudget: true creates the PDB if replicas = 1

### ISSUE THREAD

**Issue by paretl** [spotahome/redis-operator#653]
### Expected behaviour

Reduce the Pod Disruption Budgets to 0 (or not create it) when we deploy redis and/or sentinel with only 1 replica and `disablePodDisruptionBudget: true`

### Actual behaviour

Today, `disablePodDisruptionBudget: true` is creating a Pod Disruption Budgets with a minimal of 1

Maybe this condition https://github.com/spotahome/redis-operator/blob/632aa3da88ee2a28ccb9fc4f571ddcb556dbd713/operator/redisfailover/service/client.go#L88 is not working well 

When using:
```
spec:
  sentinel:
    replicas: 1
    disablePodDisruptionBudget: true
  redis:
    replicas: 1
    disablePodDisruptionBudget: true
```
for my `RedisFailover`
and the `redis-operator` with the default settings.

The redis/sentinel Pod Disruption Budgets are created with a minimum available value of 1 instead of 0.
So the variable `disablePodDisruptionBudget` doesn't really disable the PDB if the replicas is 1

When I try to evict a pod, I have the error : `Error: Cannot evict pod as it would violate the pod's disruption budget.` which is normal as the minimum available is 1.

Maybe I make something wrong :smile: if it's the case, please share me the correct way

### Steps to reproduce the behaviour

- Deploy the operator in a Kubernetes cluster
- Deploy the RedisFailover with this configuration
```
spec:
  sentinel:
    replicas: 1
    disablePodDisruptionBudget: true
  redis:
    replicas: 1
    disablePodDisruptionBudget: true
```
- At this point, we can see that the PDB is created with a minimal of 1.

### Environment

How are the pieces configured?
* Redis Operator version: 3.2.7
* Kubernetes version: v1.27.3

**Comment by ebuildy** [comment]
the condition is working well, I think you have changed this value from false to true right?

So the PDB object is not deleted.

**Comment by paretl** [comment]
> the condition is working well, I think you have changed this value from false to true right?
> 
> So the PDB object is not deleted.

Yes @ebuildy 

After removing the PDBs by hand, I have tried to change the value of `disablePodDisruptionBudget` to false and I have applied. The PDB is created, as expected
But, after removing the PDBs again and changing the value of `disablePodDisruptionBudget` to true. When I apply, the PDBs are also created. This time, this is not expected as it should be disabled.
(Tested with `replicas: 1` of course, as my example above)

I agree, the condition looks good but I can't explain this behavior.

**Comment by ebuildy** [comment]
Did you use the latest CRD / operator? I have tested several times yesterday and this is OK.

**Comment by paretl** [comment]
Thanks @ebuildy for the feedback

I tried with the latest version of the CRD/operator (v1.3.0-rc1) and the redis-operator chart version 3.3.0 and I still have the same behavior: the PDBs are created with a minimum available of 1, even if I remove them by hand before applying it

As a reminder, my configuration is:
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-cluster
spec:
  sentinel:
    replicas: 1
    disablePodDisruptionBudget: true
  redis:
    replicas: 1
    disablePodDisruptionBudget: true
```
and the operator is launched with the default values, I have just modified the image.tag to try with the latest version
