### ISSUE TITLE
Operator Helm Chart v3.3.0 fails at 1st launch

### ISSUE THREAD

**Issue by paretl** [spotahome/redis-operator#654]
### Expected behaviour

Launch the Operator Helm chart v3.3.0 (latest one today) 

### Actual behaviour

It fails fast and the error is:

```
STDERR:
Error: failed to install CRD crds/databases.spotahome.com_redisfailovers.yaml: error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
```

When digging a little bit, I saw that the `crds/databases.spotahome.com_redisfailovers.yaml` file has these lines:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- with .Values.crds.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: redisfailovers.databases.spotahome.com
```
So I guess that the go template part in `annotations` is not expected here

### Steps to reproduce the behavior

:warning: Be sure that you have no current RedisFailover CRD installed. Otherwise, there is no failure. I usually remove the entire release to be sure that everything is removed.

To reproduce, launch the `redis-operator` chart with v3.3.0.

### Environment

How are the pieces configured?
* Redis Operator version: v1.3.0-rc1 but it fails for any versions
* Kubernetes version: v1.27

### Logs

There is no more details about this error in the logs with the --debug flag.
