### ISSUE TITLE
Promote a Redis server that is created from Bootstrap Node become a master node

### ISSUE THREAD

**Issue by tasszz2k** [spotahome/redis-operator#664]
Hi,

Thanks for your work on this operator. 🫡

---
In my case, I want to move all the Redis resources to another server without downtime. I have tried to use the [Bootstrap Node configuration](https://github.com/spotahome/redis-operator#bootstrapping-from-pre-existing-redis-instances).

I want to ask: How can I promote a Redis server that is created from [Bootstrap Node](https://github.
com/spotahome/redis-operator#bootstrapping-from-pre-existing-redis-instances) become a master node?

### Expected behaviour

- Promote a new Redis server to become a master node

### Actual behaviour

- The new Redis server switches to slave mode after a few seconds. I think the `redis-operator` updates its interval.

### Steps to reproduce the behaviour

- Create a new Redis server from **Bootstrap Node** with configuration:
```yaml
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: test-switch-online-08
  namespace: redis-sentinel-dev
spec:
  bootstrapNode:
    host: "172.16.206.17" # IP of the source redis server
    port: "6379" 
    allowSentinels: true 
  auth:
    secretPath: test-switch-online-07 # password of the source redis server
  redis:
    command:
      - redis-server
      - /redis/redis.conf
      - --io-threads
      - "1"
    customConfig:
      - replica-priority 9 # I tried to set this value to different than 0 and smaller than 100 but it doesn't work
      - port 6379
      - protected-mode no
      - other custom configurations ...
```
- The Redis servers are created successfully but the `slave-priority` and `replica-priority` of 
  them still is 100
```bash
127.0.0.1:6379> config get replica-priority
1) "replica-priority"
2) "100"
```
- I tried to update the `replica-priority` of the new Redis server to 9 and  `failover` but after a few seconds, it switched to slave mode again

![image](https://github.com/spotahome/redis-operator/assets/48039235/d0b4e99d-09d0-4f5f-846a-da4089a27cae)

### Environment

* Redis Operator version: v1.2.3
* Kubernetes version: v1.21.5

### Logs
```log
time="2023-09-25T15:16:54+07:00" level=info msg="service updated" namespace=redis-sentinel-dev service=k8s.service serviceName=rfr-test-switch-online-08 src="service.go:99"
time="2023-09-25T15:16:54+07:00" level=info msg="service updated" namespace=redis-sentinel-dev service=k8s.service serviceName=rfs-test-switch-online-08 src="service.go:99"
time="2023-09-25T15:16:54+07:00" level=info msg="configMap updated" configMap=rfs-test-switch-online-08 namespace=redis-sentinel-dev service=k8s.configMap src="configmap.go:84"
time="2023-09-25T15:16:54+07:00" level=info msg="configMap updated" configMap=rfr-s-test-switch-online-08 namespace=redis-sentinel-dev service=k8s.configMap src="configmap.go:84"
time="2023-09-25T15:16:54+07:00" level=info msg="configMap updated" configMap=rfr-readiness-test-switch-online-08 namespace=redis-sentinel-dev service=k8s.configMap src="configmap.go:84"
time="2023-09-25T15:16:54+07:00" level=info msg="configMap updated" configMap=rfr-test-switch-online-08 namespace=redis-sentinel-dev service=k8s.configMap src="configmap.go:84"
time="2023-09-25T15:16:54+07:00" level=info msg="service updated" namespace=redis-sentinel-dev service=k8s.service serviceName=rfr-test-switch-online-08-0 src="service.go:99"
time="2023-09-25T15:16:54+07:00" level=info msg="service updated" namespace=redis-sentinel-dev service=k8s.service serviceName=rfr-test-switch-online-08-1 src="service.go:99"
time="2023-09-25T15:16:54+07:00" level=info msg="podDisruptionBudget updated" namespace=redis-sentinel-dev podDisruptionBudget=rfr-test-switch-online-08 service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2023-09-25T15:16:54+07:00" level=info msg="statefulSet updated" namespace=redis-sentinel-dev service=k8s.statefulSet src="statefulset.go:108" statefulSet=rfr-test-switch-online-08
time="2023-09-25T15:16:54+07:00" level=info msg="podDisruptionBudget updated" namespace=redis-sentinel-dev podDisruptionBudget=rfs-test-switch-online-08 service=k8s.podDisruptionBudget src="poddisruptionbudget.go:85"
time="2023-09-25T15:16:55+07:00" level=info msg="deployment updated" deployment=rfs-test-switch-online-08 namespace=redis-sentinel-dev service=k8s.deployment src="deployment.go:109"

```

**Comment by tasszz2k** [comment]
According to the documentation

> Note: Redis instance will always be configured with replica-priority 0. This means that these Redis instances can never be promoted to a master.

Why must we prevent these Redis instances from being promoted to master?

Should we provide another option so that the client can override this configuration?

---
This code has a problem when the `customConfig` contains a config `replica-priority x` and `x` is different than `0` or `100` depending on the `bootstrap` config. So the `customConfig` is:
```yaml
customConfig:
  - replica-priority 0
  - # other custom configurations
  - replica-priority x # duplicate replica-priority parameter
```

**validate.go**
```go
// ...
// Validate set the values by default if not defined and checks if the values given are valid
func (r *RedisFailover) Validate() error {
	if len(r.Name) > maxNameLength {
		return fmt.Errorf("name length can't be higher than %d", maxNameLength)
	}

	if r.Bootstrapping() {
		if r.Spec.BootstrapNode.Host == "" {
			return errors.New("BootstrapNode must include a host when provided")
		}

		if r.Spec.BootstrapNode.Port == "" {
			r.Spec.BootstrapNode.Port = strconv.Itoa(defaultRedisPort)
		}
		r.Spec.Redis.CustomConfig = deduplicateStr(append(bootstrappingRedisCustomConfig, r.Spec.Redis.CustomConfig...))
	} else {
		r.Spec.Redis.CustomConfig = deduplicateStr(append(defaultRedisCustomConfig, r.Spec.Redis.CustomConfig...))
	}
// ...

}

// ...
func deduplicateStr(strSlice []string) []string {
	allKeys := make(map[string]bool)
	list := []string{}
	for _, item := range strSlice {
		if _, value := allKeys[item]; !value {
			allKeys[item] = true
			list = append(list, item)
		}
	}
	return list
}
```

**Comment by tasszz2k** [comment]
I guess that the Redis sentinels reset the master every few seconds. But I don't know how to prevent it. :"<<

**This is the logs of the redis sentinel**
```log
sentinel 1:X 25 Sep 2023 09:43:54.094 # +reset-master master mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:43:54.100 # +reset-master master mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:43:54.103 # +set master mymaster 172.16.206.17 6379 down-after-milliseconds 5000
sentinel 1:X 25 Sep 2023 09:43:54.105 # +set master mymaster 172.16.206.17 6379 failover-timeout 15000
sentinel 1:X 25 Sep 2023 09:43:54.107 # +set master mymaster 172.16.206.17 6379 parallel-syncs 2
sentinel 1:X 25 Sep 2023 09:43:54.747 * +sentinel sentinel 02c5f4a412bbb573229a3e8027d30df7e3400387 172.16.23.138 26379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:43:54.756 * +sentinel sentinel 47e6834cdab6815ae9c7491da4cd2ddaa99c81d3 172.16.206.163 26379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:43:54.963 * +sentinel sentinel 91e738aa506300c69a20b467bb92649bf4314517 172.16.80.163 26379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:43:55.085 * +sentinel sentinel 31af2ece171d738c9409561da7026d7aca61c464 172.16.23.225 26379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:43:55.954 * +sentinel sentinel 9ded5824f47023ae9f46ce19df6ca9955270e1a3 172.16.206.143 26379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:44:00.364 * +slave slave 172.16.80.228:6379 172.16.80.228 6379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:44:00.365 * +slave slave 172.16.206.180:6379 172.16.206.180 6379 @ mymaster 172.16.206.17 6379
sentinel 1:X 25 Sep 2023 09:44:00.367 * +slave slave 172.16.80.218:6379 172.16.80.218 6379 @ mymaster 172.16.206.17 6379
```

**Comment by tasszz2k** [comment]
I discovered that although `redis-sentinel` updates the new `redis-server` to the master node, the `redis-operator` doesn't update the `redisfailovers-role` of the Redis servers. So, this is the reason why the new Redis server switches to slave mode again.

```yaml
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: redis-operator
    app.kubernetes.io/name: test-switch-online-08
    app.kubernetes.io/part-of: redis-failover
    controller-revision-hash: rfr-test-switch-online-08-56b8559f9b
    redisfailovers-role: slave
    redisfailovers.databases.spotahome.com/name: test-switch-online-08
    statefulset.kubernetes.io/pod-name: rfr-test-switch-online-08-0
  name: rfr-test-switch-online-08-0
  namespace: redis-sentinel-dev
  ```
