### ISSUE TITLE
Auth from ConfigMap

### ISSUE THREAD

**Issue by sergey-kudriavtsev** [spotahome/redis-operator#684]
### Expected behaviour
Don`t use configmap for masterauth and requirepass
Please add authorization to bootstrapNode from own secret 

### Actual behaviour

now you are exposing the original secret

### Proposal

I suggest
1 - finalize the section
```yml
   auth:
     secretName: <-- It secret Name
     secretPath: <-- It secret Path (default password)
```
2 - create a similar subsection in bootstrapNode
3 - **exclude masterauth and requirepass from ConfigMap**
      Use a original secret (auth)
