### ISSUE TITLE
Unable to modify probes

### ISSUE THREAD

**Issue by jonathon2nd** [spotahome/redis-operator#692]
### Expected behaviour

Modify the default livenessProbe for redis

### Actual behaviour

Nothing happens when I attempt to use [custom probes](https://github.com/spotahome/redis-operator/pull/560)

### Steps to reproduce the behaviour

Deploy the following under redis spec in RedisFailovers

```
    customLivenessProbe:
      exec:
        command:
          - sh
          - '-c'
          - >-
            redis-cli -h 127.0.0.1 -p 6379 ping --user pinger --pass
            pingpass --no-auth-warning
```

### Environment

How are the pieces configured?
* Redis Operator version: 3.2.9
* Kubernetes version: v1.26.13+rke2r1

### Logs

No operator logs that are useful.
