### ISSUE TITLE
Can't load more users into Redis kubernetes deployment

### ISSUE THREAD

**Issue by dgaddsec** [spotahome/redis-operator#693]
### Expected behaviour

Deploy Spotahome Redis into my cluster with the more than default users created during deployment.

### Actual behaviour

Redis is deployed correctly, but have only `default` and `pinger` users.

### Steps to reproduce the behaviour

I used Spotahome Redis operator in my Kubernetes deployment. I have my own operator written in C#. It is deployed correctly in general.
I have prepared a secret that contains ACL commands that should add 3 users.
I mount it as a file that is accessible through Redis pod.
I set `aclfile` property in `customConfig` property  

Please find below my main `.yaml` template for RedisFailover:

```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
  namespace: default
  labels:
    ...
spec:
  redis:
    image: redis:7.2.4-alpine
    imagePullPolicy: IfNotPresent
    replicas: 3
    resources:
      ...
    affinity:
      ...
    podAnnotations:
      ...
    extraVolumes:
    - name: redis-users-volume
      secret:
        secretName: redis-users-list
        optional: false
    extraVolumeMounts:
    - name: redis-users-volume
      mountPath: /etc/redis
      readOnly: true
    customConfig:
      - "slowlog-log-slower-than 9500" # works
      - "aclfile ./etc/redis/users.acl" # doesn't work
  sentinel:
    ...
```

Here is a RedisFailover Describe result:

![image](https://github.com/spotahome/redis-operator/assets/144250809/5f9f061d-b57b-44c1-ab37-c00eb172865d)

And below there is screenshot from Redis pod shell console presenting:
- succesfully mounting secret into a file with a correct content
- loaded users in acl
- config values of `aclfile` and `slowlog-log-slower-than`
- result from the unsuccessful try of setting `aclfile` config
![image](https://github.com/spotahome/redis-operator/assets/144250809/96badf30-9df6-465d-b323-19f9428b341e)

Interesting point is that `slowlog-log-slower-than` sets correctly (9500 is not a default value), while `aclfile` is not.

### Environment

**Redis version**
redis_version:7.2.4

**Kubectl version**
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.11+vmware.1-fips.1

### Question

How can I set up more users?
