### ISSUE TITLE
Feature request: More granularity in affinity settings 

### ISSUE THREAD

**Issue by francoispqt** [spotahome/redis-operator#94]
Hi,

Thanks for the operator it works as expected.

We'd like to ask if we can add some granularity to affinity settings. 
Our use case is to have hard affinity on nodes and soft affinity on zones (we are hosted on aws in 3 different availability zones). 

The k8s built-in affinity syntax would be fine
```
 affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: data
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
            - topologyKey: "failure-domain.beta.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: data
```

We can submit an MR if you don't have much time to work on it. 

Thanks
