### ISSUE TITLE
customConfig make no failover

### ISSUE THREAD

**Issue by tigran-a** [spotahome/redis-operator#95]
### Motivation
I'm trying to have pure in-memory fail-resistant redis with no using disk and memory-only replication. While debugging where it stops working, came up with the described below small configuration, based on the example config file.

By the way, would be good to have a possibility of replicas = 2 for the redis. For now it does not create anything if 2 is set.

### Expected behaviour

After deleting a master pod, failover happens and it becomes a slave with synced data

### Actual behaviour

Previously deleted master becomes a slave (no master in a cluster) and at some point becomes a master and overwrites the data on slaes

### Steps to reproduce the behaviour

`kubectl create -f all-options.yaml`

(taken from the examples, added customConfig save "") 

```
apiVersion: storage.spotahome.com/v1alpha2
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  hardAntiAffinity: false                    # Optional. Value by default. If true, the pods will not be scheduled on the same node.
  sentinel:
    replicas: 3                              # Optional. 3 by default, can be set higher.
    resources:                               # Optional. If not set, it won't be defined on created reosurces.
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    customConfig: []                         # Optional. Empty by default.
  redis:
    replicas: 3                              # Optional. 3 by default, can be set higher.
    image: redis                             # Optional. "redis" by default.
    version: 3.2-alpine                      # Optional. "3.2-alpine" by default.
    resources:                               # Optional. If not set, it won't be defined on created reosurces
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    exporter: false                          # Optional. False by default. Adds a redis-exporter container to export metrics.
    exporterImage: oliver006/redis_exporter  # Optional. oliver006/redis_exporter by default.
    exporterVersion: v0.11.3                 # Optional. v0.11.3 by default.
    storage:
      emptyDir: {}                           # Optional. emptyDir by default.
    customConfig: ['save ""']                         # Optional. Empty by default.
```

- setting a test value on master
`kubectl exec -it rfr-redisfailover-0 redis-cli set test '11111'                 `  
```
OK
```

- checking replication
for i in {0..2}; do kubectl exec -it rfr-redisfailover-$i redis-cli get test; done
```
"11111"
"11111"
"11111"
```

- deleting master
` kubectl delete pod rfr-redisfailover-0 `

- waiting replacement is up (optional) 
```
kubectl get pods | grep fail
redisfailover-redisoperator-7c86977464-c2hln   1/1       Running   1          21h
rfr-redisfailover-0                            1/1       Running   0          1m
rfr-redisfailover-1                            1/1       Running   0          9m
rfr-redisfailover-2                            1/1       Running   0          7m
rfs-redisfailover-6784b94555-8dmv9             1/1       Running   0          10m
rfs-redisfailover-6784b94555-n5nkk             1/1       Running   0          10m
rfs-redisfailover-6784b94555-v9kd7             1/1       Running   0          10m
```

- checking values of the test key:
`for i in {0..2}; do kubectl exec -it rfr-redisfailover-$i redis-cli get test; done`
```
(nil)
"11111"
"11111"
```
 (expected not (nil) )

- after some time -0 was set again as master,  
` for i in {0..2}; do kubectl exec -it rfr-redisfailover-$i redis-cli get test; done`
```
(nil)
(nil)
(nil)
```

### Environment

How are the pieces configured?
* git commit hash 198ad916932b29c387d347cacd74f0b52008c93d
*
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
#### `kubectl logs rfr-redisfailover-0`
```
... (lots of  MASTER aborted replication with an error: ERR Can't SYNC while not connected with my master before )
1:S 20 Sep 12:01:55.161 * Retrying with SYNC...
1:S 20 Sep 12:01:55.161 # MASTER aborted replication with an error: ERR Can't SYNC while not connected with my master
1:S 20 Sep 12:01:56.162 * Connecting to MASTER 127.0.0.1:6379
1:S 20 Sep 12:01:56.162 * MASTER <-> SLAVE sync started
1:S 20 Sep 12:01:56.162 * Non blocking connect for SYNC fired the event.
1:S 20 Sep 12:01:56.162 * Master replied to PING, replication can continue...
1:S 20 Sep 12:01:56.162 * Partial resynchronization not possible (no cached master)
1:S 20 Sep 12:01:56.162 * Master does not support PSYNC or is in error state (reply: -ERR Can't SYNC while not connected with my master)
1:S 20 Sep 12:01:56.162 * Retrying with SYNC...
1:S 20 Sep 12:01:56.162 # MASTER aborted replication with an error: ERR Can't SYNC while not connected with my master
1:M 20 Sep 12:01:57.144 * MASTER MODE enabled (user request from 'id=143 addr=10.244.6.89:53622 fd=6 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=slaveof')
1:M 20 Sep 12:01:57.341 * Slave 10.244.6.102:6379 asks for synchronization
1:M 20 Sep 12:01:57.341 * Full resync requested by slave 10.244.6.102:6379
1:M 20 Sep 12:01:57.341 * Starting BGSAVE for SYNC with target: disk
1:M 20 Sep 12:01:57.341 * Background saving started by pid 129
129:C 20 Sep 12:01:57.383 * DB saved on disk
129:C 20 Sep 12:01:57.383 * RDB: 0 MB of memory used by copy-on-write
1:M 20 Sep 12:01:57.465 * Background saving terminated with success
1:M 20 Sep 12:01:57.465 * Synchronization with slave 10.244.6.102:6379 succeeded
1:M 20 Sep 12:01:57.789 * Slave 10.244.7.27:6379 asks for synchronization
1:M 20 Sep 12:01:57.789 * Full resync requested by slave 10.244.7.27:6379
1:M 20 Sep 12:01:57.789 * Starting BGSAVE for SYNC with target: disk
1:M 20 Sep 12:01:57.789 * Background saving started by pid 130
130:C 20 Sep 12:01:57.977 * DB saved on disk
130:C 20 Sep 12:01:57.977 * RDB: 0 MB of memory used by copy-on-write
1:M 20 Sep 12:01:58.066 * Background saving terminated with success
1:M 20 Sep 12:01:58.066 * Synchronization with slave 10.244.7.27:6379 succeeded
```

#### `kubectl logs rfr-redisfailover-1`
```
1:S 20 Sep 12:01:45.767 # Error condition on socket for SYNC: Host is unreachable
1:S 20 Sep 12:01:46.287 * Connecting to MASTER 10.244.4.32:6379
1:S 20 Sep 12:01:46.287 * MASTER <-> SLAVE sync started
1:S 20 Sep 12:01:48.840 # Error condition on socket for SYNC: Host is unreachable
1:S 20 Sep 12:01:49.318 * Connecting to MASTER 10.244.4.32:6379
1:S 20 Sep 12:01:49.318 * MASTER <-> SLAVE sync started
1:S 20 Sep 12:01:51.911 # Error condition on socket for SYNC: Host is unreachable
1:S 20 Sep 12:01:52.325 * Connecting to MASTER 10.244.4.32:6379
1:S 20 Sep 12:01:52.325 * MASTER <-> SLAVE sync started
1:S 20 Sep 12:01:54.984 # Error condition on socket for SYNC: Host is unreachable
1:S 20 Sep 12:01:55.331 * Connecting to MASTER 10.244.4.32:6379
1:S 20 Sep 12:01:55.332 * MASTER <-> SLAVE sync started
1:S 20 Sep 12:01:57.145 * Discarding previously cached master state.
1:S 20 Sep 12:01:57.145 * SLAVE OF 10.244.4.34:6379 enabled (user request from 'id=415 addr=10.244.6.89:52874 fd=7 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=slaveof')
1:S 20 Sep 12:01:57.339 * Connecting to MASTER 10.244.4.34:6379
1:S 20 Sep 12:01:57.339 * MASTER <-> SLAVE sync started
1:S 20 Sep 12:01:57.339 * Non blocking connect for SYNC fired the event.
1:S 20 Sep 12:01:57.340 * Master replied to PING, replication can continue...
1:S 20 Sep 12:01:57.341 * Partial resynchronization not possible (no cached master)
1:S 20 Sep 12:01:57.341 * Full resync from master: d905b284f63590b68e458ad7e7c18529598bf53b:1
1:S 20 Sep 12:01:57.465 * MASTER <-> SLAVE sync: receiving 77 bytes from master
1:S 20 Sep 12:01:57.465 * MASTER <-> SLAVE sync: Flushing old data
1:S 20 Sep 12:01:57.466 * MASTER <-> SLAVE sync: Loading DB in memory
1:S 20 Sep 12:01:57.466 * MASTER <-> SLAVE sync: Finished with success
1:S 20 Sep 12:07:37.042 * 1 changes in 900 seconds. Saving...
1:S 20 Sep 12:07:37.043 * Background saving started by pid 1475
1475:C 20 Sep 12:07:37.073 * DB saved on disk
1475:C 20 Sep 12:07:37.073 * RDB: 0 MB of memory used by copy-on-write
1:S 20 Sep 12:07:37.143 * Background saving terminated with success
```

## More

while trying to re-reproduce, got another as-for-me-strange behavior: all pods are ready, but no master elected (the same config) 
```
kubectl get pods | grep fail
redisfailover-redisoperator-7c86977464-c2hln   1/1       Running   1          21h
rfr-redisfailover-0                            1/1       Running   0          4m
rfr-redisfailover-1                            1/1       Running   0          2m
rfr-redisfailover-2                            1/1       Running   0          1m
rfs-redisfailover-6784b94555-8rxv5             1/1       Running   0          4m
rfs-redisfailover-6784b94555-bdf52             1/1       Running   0          4m
rfs-redisfailover-6784b94555-tq7dj             1/1       Running   0          4m
➜  ~ kubectl exec -it rfr-redisfailover-0 redis-cli set test '11111' 
(error) READONLY You can't write against a read only slave.
➜  ~ kubectl exec -it rfr-redisfailover-1 redis-cli set test '11111' 
(error) READONLY You can't write against a read only slave.
➜  ~ kubectl exec -it rfr-redisfailover-2 redis-cli set test '11111' 
(error) READONLY You can't write against a read only slave.
```

after some small time master was set to 0
``` 
kubectl exec -it rfr-redisfailover-0 redis-cli set test '11111' 
OK
```
